version: '3.7'
services:
  proxy:
    image: "nginx:1.17.6"
    links:
      - wordpress
    volumes:
      - ./nginx:/etc/nginx
      - ./static:/var/www/default
    ports:
      - "80:80"
  wordpress:
    image: wordpress
    links:
      - mariadb:mysql
    environment:
      - "WORDPRESS_DB_PASSWORD=$WORDPRESS_PASSWORD"
    volumes:
      - ./html:/var/www/html
  mariadb:
    image: mariadb
    environment:
      - "MYSQL_ROOT_PASSWORD=$WORDPRESS_PASSWORD"
      - MYSQL_DATABASE=wordpress
    volumes:
      - ./database:/var/lib/mysql
  ontheplate:
    image: "rmichele/fat-squirrel:$SQUIRREL_TAG"
    links:
      - mongodb
    environment:
      - "PORT=80"
      - "MONGODB_URI=mongodb://mongodb:27017/squirrel"
  mongodb:
    image: "mongo:4.2.1"
    volumes:
      - ./squirrel_data:/data/db